### ISSUE TITLE
Cmake should handle linear algebra dependencies better

### ISSUE THREAD

**Issue by bremerm31** [UT-CHG/dgswemv2#112]
Cmake requires both blaze and eigen, whereas, I think if either one is found the code should be able to compile.

**Comment by bremerm31** [comment]
@kazbekkm can this be closed now?

**Comment by kazbekkm** [comment]
I think so.

**Comment by bremerm31** [comment]
Fixed in d1d7eef0d7969bf39b5d746cdb1818371318ded1
